stages:
  - build
  - push

variables:
  VERSION: $CI_COMMIT_REF_SLUG
  IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

Image:
  stage: build
  tags: [ shell ]
  script: docker build -t ${IMAGE_NAME} -f Dockerfile .

Push:
  stage: push
  tags: [ shell ]
  only: [ tags, master, develop ]
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script: docker push ${IMAGE_NAME}
